version: "3.7"
services:
    db:
        image: "mysql:5.7"
        volumes:
            - db_data:/var/lib/mysql
        environment: 
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: zabbix
          MYSQL_USER: zbuser
          MYSQL_PASSWORD: zbxp@ss
       # deploy:
           # constraints: [node.role == manager]
        networks: 
            - backend
    backend:
        image: zabbix/zabbix-server-mysql
        depends_on: 
            - db
        environment:
            DB_SERVER_HOST: db
            DB_SERVER_PORT: 3306
            MYSQL_USER: zbuser
            MYSQL_PASSWORD: zbxp@ss
            MYSQL_DATABASE: zabbix
        #deploy:
           # constraints: [node.role == manager]
        ports:
            - 10051:10051
        networks: 
            - backend
    frontend:
        image: zabbix/zabbix-web-nginx-mysql
        depends_on: 
            - backend
        environment: 
            ZBX_SERVER_HOST: backend
            ZBX_SERVER_PORT: 10051
            DB_SERVER_HOST: db
            DB_SERVER_PORT: 3306
            MYSQL_USER: zbuser
            MYSQL_PASSWORD: zbxp@ss
            MYSQL_DATABASE: zabbix
            PHP_TZ: America/Sao_Paulo
        deploy:
            replicas: 4
        ports:
            - 8080:8080 
        networks: 
            - backend
            - frontend
volumes:
    db_data:
networks: 
    backend:
    frontend: